config/routes.rb
DemoCloud::Application.routes.draw do 
 
  mount Ckeditor::Engine => '/ckeditor'

  resources :comments
  
  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

 resources :authentications
 
 resources :courses do
   post "rate", :on=> :member
 end
 
 match "pages/:id" ,:to => "pages#show"
 
 match '/auth/:provider/callback' => 'authentications#create' 
 match '/users/validations/check_email', :to=>"users#check_email"
 
 get "password_resets/new"

 match '/change_password', :controller => 'users', :action => 'change_password'
 
  match 'users/my_profile' ,:to =>'users#my_profile'
  match 'users/about_us' ,:to =>'users#about_us'
  match 'users/help' ,:to =>'users#help'
  match 'users/how_it_works' ,:to =>'users#how_it_works'
  match 'users/account_setting' ,:to =>'users#account_setting'
 resources :users do
    get "is_authenticated", :on=> :member
 end
  
  resources :sessions, :only => [:new,:create,:destroy,:edit]
  
  root :to => 'homes#index'
  
  match 'dashboard' => 'users#dashboard', :as => 'user_root'
  match '/user_signup', :to =>'users#new'
  match '/user_signin', :to =>'sessions#new'
  match  '/users/:id/edit',  :to => "users#edit" 
  match '/user_signout', :to =>'sessions#destroy'
  
  resources :password_resets

end

app/models/user.rb
require 'digest'
class User < ActiveRecord::Base
  
  ajaxful_rateable :dimensions => [:behavior]
  ajaxful_rater
  
  attr_accessor :password
  attr_accessible :name, :email, :password, :password_confirmation, :role_ids, :user_id, :is_authenticated
   
 
  
  email_regex = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  validates :email, :presence => true,
                    :format => { :with => email_regex},
                    :uniqueness => { :case_sensitive => false }

  validates :password,  :confirmation => false
	
  before_save :encrypt_password
  before_create { generate_token(:auth_token) }

  has_many :authentications, :dependent => :destroy
  
  # Method for Omniauth Application. Called at authentications controller.
  def apply_omniauth(auth)
    # In previous omniauth, 'user_info' was used in place of 'raw_info'
    self.email = auth['extra']['raw_info']['email']
    # Again, saving token is optional. If you haven't created the column in authentications table, this will fail
    authentications.build(:provider => auth['provider'], :uid => auth['uid'], :token => auth['credentials']['token'])
  end 
  
  # This Method is for allowing authentication via link mailed to the user while registering. 
  def authenticated_via_link
    self.is_authenticated == true
  end
  
  def send_password_reset
    generate_token(:password_reset_token)
    self.password_reset_sent_at = Time.zone.now
    save!
    UserMailer.password_reset(self).deliver
  end

  def generate_token(column)
    begin
      self[column] = SecureRandom.urlsafe_base64
    end while User.exists?(column => self[column])
  end
 
  def has_password?(submitted_password)
    encrypted_password == encrypt(submitted_password)
  end
  
class << self
  def authenticate(email, submitted_password)
    user = find_by_email(email)
    (user && user.has_password?(submitted_password)) ? user :nil  
  end
    
  def authenticate_with_salt(id,cookie_salt)
    user = find_by_id(id)
    (user && user.salt == cookie_salt) ? user :nil
  end 
 
end

private
  def encrypt_password
    self.salt = make_salt if new_record?
    self.encrypted_password = encrypt(password)
  end
 
  def encrypt(string)
    secure_hash("#{salt}--#{string}")
  end
 
  def make_salt
    secure_hash("#{Time.now.utc}--#{password}")
  end
 
  def secure_hash(string)
    Digest::SHA2.hexdigest(string)
  end
 
  def role?(role)
    return !!self.roles.find_by_name(role.to_s)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate, :only => [:edit, :update, :my_profile, :dashboard]
  before_filter :correct_user, :only => [:edit, :update]
  layout 'dashboard'
  def show
    @user = User.find(params[:id])
   
  end
  def rate
    @course = Course.all
    @course.rate(params[:stars], current_user, params[:dimension])
    render :update do |page|
      page.replace_html @course.wrapper_dom_id(params), ratings_for(@course, params.merge(:wrap => false))
      page.visual_effect :highlight, @course.wrapper_dom_id(params)
  end
 end
 
 
 
  def new
    @user = User.new
    @title="Sign up"
  end
 
  def dashboard
    @users = User.all
    @course = Course.all
    
    if !params[:value].nil?
      @courses = Course.find_all_by_course_category(params[:value])
    else
      @courses = Course.find(:all,:order => "is_featured DESC")
    end 
    
    
    #calculate discount
  
   
    
    
  end
  def my_profile
   
  end
  def account_setting
   
  end
  def about_us
   
  end
  def help
   
  end
  def how_it_works
   
  end
  
  def create
    @user = User.new(params[:user])
    if @user.save && UserMailer.authenticate_registration(@user).deliver 
      redirect_to root_url, notice: "Please check your email for verification link #{@user.email}"
      
    else
      @title = "Sign up"
      render 'new'
    end
 
  end

  def edit
    @user = User.find(params[:id])
    @title = "Edit user"
  end

  def update
    @user = User.find(params[:id])
    if (User.authenticate(@user.email, params[:user][:password]) == @user) || (@user.authentications && (@user.encrypted_password == nil))
      if @user.update_attributes(params[:user])
        flash[:success] = "Profile updated Successfully."
        redirect_to users_my_profile_path
      else
        @title = "Edit user"
        render 'edit'
      end 
    else
      flash[:error] = "Profile not updated. Enter Correct Password"
      render 'edit'
    end 
  end
  
  
  def check_email
      @user = User.find_by_email(params[:user][:email]) 
        respond_to do |format|
            format.json { render :json => !@user }
       end
  end
 
  def change_password
    @user = User.find(current_user.id)
    if request.post?
      if (User.authenticate(@user.email, params[:change_password][:old_password]) == @user) || (@user.authentications && (@user.encrypted_password == nil))
        @user.password = params[:change_password][:new_password]
        @user.password_confirmation =
        params[:change_password][:new_password_confirmation]

        if @user.save
          flash[:notice] = 'Password successfully updated!'
          redirect_to @user
        else
          flash[:error] = 'New password mismatch.'
          render :action => 'change_password'
        end
      
      else
          flash[:error] = 'Old password incorrect.'
          render :action => 'change_password'
      end
    end
  end
 
  def is_authenticated
    @user =  User.find_by_id(params[:id])
    @user.update_column(:is_authenticated, true)
    redirect_to root_path, :flash => {:success => "Congratulations Profile verified! Please login."}
  end
  
  
    
  private
  def authenticate
    deny_access unless signed_in?
  end
  
  def correct_user
    @user = User.find(params[:id])
    redirect_to(root_path) unless current_user=(@user)
  end

  
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/about_us.html.erb
<div class="tutorial_container" style="padding:20px 10px">
  <div class="righttd" style="margin-bottom:20px"><strong><div class="title">About Us</div></strong>
  </div>

  
  <div>

<table width="520" border="0" cellspacing="10" cellpadding="0" style="font-size:18px">
<strong><div class="txt">  Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam arcu magna, luctus in feugiat nec, ullamcorper eu metus. Cras vitae diam eros. Mauris tempus auctor commodo.
Aliquam facilisis tristique augue sed cursus. Morbi faucibus volutpat augue eget tempor. Vestibulum risus orci, rutrum ac auctor ac, convallis vel orci.</p> <strong><div class="txt"> Donec dignissim libero orci, ut porta eros. Quisque fermentum, nisi vel molestie ultrices, sapien mi semper felis, id porta lorem lacus non risus. Donec tellus diam, aliquet in mollis quis, dapibus in arcu.</div></p></strong>
	
	<div class="txt1">
	<ul style="color:#000000">
	<strong><li>Aliquam condimentum augue in neque dictum id adipiscing tellus tempus.</li></strong>
	<strong><li>Praesent vestibulum facilisis eros, et tempus leo imperdiet sit amet.</li></strong>
	<strong><li>Sed iaculis magna sed lectus pulvinar sodales.</li></strong>
	<strong><li>Suspendisse ultrices posuere tortor, ac pretium ante pretium nec.</li></strong>
	<strong><li>Etiam vel urna ligula, at porta velit.</li></strong>
	<strong><li>Praesent a turpis ac metus consectetur porta ullamcorper ut magna.</li></strong>
	</ul></div>


      <strong><div class="txt">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam arcu magna, luctus in feugiat nec, ullamcorper eu metus. Cras vitae diam eros. Mauris tempus auctor commodo. Aliquam facilisis tristique augue sed cursus. Morbi faucibus volutpat augue eget tempor. </div></strong>
	  
	  <strong><p><div class="txt">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam arcu magna, luctus in feugiat nec, ullamcorper eu metus. Cras vitae diam eros. Mauris tempus auctor commodo. </div></strong></p>
  
    
</table>

</div>


    </div>

	</div>

app/views/users/account_setting.html.erb
	<div class="tutorial_container2">
   	 <div class="leftmenu_div">
			<div style="text-align:center; margin:20px 0 "><h1>My Account</h1></div>
			<ul id="blueblock">
				<li><a href="#">Account Setting</a></li>
			</ul>
	</div>
		
	<div class="rightside_div">
		
	<div class="profile_wrap">
	
	<table width="100%" border="0" cellspacing="5" cellpadding="5">
 	 <tr>
   
 	 </tr>
	  <tr>
   
 	 </tr>
 	 <tr>
  	  <td><%= link_to "Change my password",  change_password_path,:class =>"cp" %><br />
   	  <%= link_to "Change my email address", edit_user_path(current_user),:class =>"cp" %></td>
 	 </tr>

</table>

	</div>
	</div>
	
	</div>
    </div>

app/views/users/change_password.html.erb
<div class="tutorial_container" style="padding:20px 10px">
  <div class="righttd" style="margin-bottom:20px">Integer rhoncus leo in leo egestas a dignissim quam dapibus.Nulla volutpat libero ut quam accumsan in cursus libero porta.
In eu tortor vel quam ullamcorper sodales.</div>

<div>

<table width="520" border="0" cellspacing="10" cellpadding="0" style="font-size:18px">
	<%= form_for :change_password do |f|  %>
  <tr>
    <td align="left" valign="middle">Current password:</td>
    <td align="right" valign="top">
     <%= f.password_field :old_password,:class=>"textfield_1",:style=>" !important" %> </td>
  </tr>
  <tr>
    <td align="left" valign="middle">Password:</td>
    <td align="right" valign="top">
      <%= f.password_field :new_password,:class=>"textfield_1" %></td>
  </tr>
  <tr>
    <td align="left" valign="middle">Confirm password:</td>
    <td align="right" valign="top" class="righttd"><%= f.password_field :new_password_confirmation,:class=>"textfield_1",:style=>" !important" %></td>
  </tr>
  
    <tr>
    <td align="left" valign="top"></td>
    <td align="right" valign="top">
	 <%= link_to "Cancel",  change_password_path,:class =>"deal",:style=>"float:right; margin-left:10px" %>
     <%= f.submit 'Change Password',:class=>"deal",:style=>"float:right" %>
	    </td>
  </tr>
</table>
<% end %>

</div>


    </div>
    
   </div>  

app/views/users/dashboard.html.erb
  
<div class="tutorial_container">
<div class="tab_link"><%= link_to "All Tutorials", :controller =>"users" , :action =>"dashboard" %><%= link_to "Web Tutorials", :controller =>"users" , :action =>"dashboard",:value=>"Webtutorial" %><%= link_to "App Tutorials", :controller =>"users" , :action =>"dashboard",:value=>"Apptutorial" %> </div>
	
	<div class="result_count"><%= @courses.length %> results</div>
   <% @courses.each do |course|%>
	<div class="tutorials_box_highlight">
	
	<div class="tutorials_box_left">
	
	<div class="tutorial_image"><%= link_to image_tag("#{course.image_url(:normal1)}"),course %></div>
	
	<!-- <div style="width:auto; float:left; text-align:center; margin:10px 0 0 10px">
	
	 	  <%= ratings_for course, :dimension => :quality rescue "" %>
	
	</div> -->
	<div class="rating star<%= course.courserating %>"></div>
	 
	</div>
	
	<div class="tutorials_box_right">
	<div><%= link_to course.course_title,course,:class =>"tutorial_heading" %>.</div>

<div class="tutorial_discription"><%= course.course_summary.html_safe %> </div>


<div class="button_wraper">


<div style="float:left; margin:0 0 0 10px; width:auto"><%= link_to "VIEW THIS COURSE", course ,:class =>"deal"%></div> 

  <% @calculate_discount = ((course.percent_off || 1)/100)*((course.price))%>
  
  <% @total_discount = (course.price)-(@calculate_discount) %>
  
  <div style="margin:0 0 0 10px; float:left"><span class="price">$<%= number_with_precision(@total_discount,  :precision => 0) %></span> &nbsp;<span class="discount">$<%= course.price %></span><span class="off2"> (<%= number_with_precision(course.percent_off,  :precision => 0) %>% OFF)</span></div>
  
  <% @a= ( course.ExpiryDate - Date.today ).to_i rescue ""%> 
  	 
	<% if @a < 0 %>
	
	<div style="margin:0; float:left; width:100%; margin:10px 0"><span class="expires">Expires:</span><%=" Sorry  Course has been expired" %></div>
	<%else%>
			<div style="margin:0; float:left; width:100%; margin:10px 0"><span class="expires">Expires:</span><span class="days"> <%= a= ( course.ExpiryDate - Date.today ).to_i rescue ""%> Days</span></div>
	<% end %>
  
  </div>

		</div>
	         <% if course.is_featured == true %>
			<div class="featured_ribbon"><img src="/assets/featured.png" alt="" /></div>
		<%else%>
	       <div class="featured_ribbon"></div>
	    <% end %>	
	</div>
	
	<%end%>
			
	</div>
	</div>
	


	  

app/views/users/edit.html.erb
<div class="tutorial_container" style="padding:20px 10px">
  <div class="righttd" style="margin-bottom:20px">Integer rhoncus leo in leo egestas a dignissim quam dapibus.Nulla volutpat libero ut quam accumsan in cursus libero porta.
In eu tortor vel quam ullamcorper sodales.</div>

<div>

<table width="520" border="0" cellspacing="10" cellpadding="0" style="font-size:18px">
	<%= form_for(@user) do |f| %>
	
	
  <tr>
    <td align="left" valign="middle">New Email Address:</td>
    <td align="right" valign="top">
      <%=  f.text_field :email,:class=>"textfield_1",:style=>" !important" %>     </td>
  </tr>
  <tr>
    <td align="left" valign="middle">Password:</td>
    <td align="right" valign="top">
    <%=  f.password_field :password ,:class=>"textfield_1",:style=>" !important" %>   </td>
  </tr>
  <tr>
    <td align="left" valign="middle">Confirm password:</td>
    <td align="right" valign="top" class="righttd">  <%=  f.password_field :password_confirmation,:class=>"textfield_1",:style=>" !important" %> </td>
  </tr>
  
    <tr>
    <td align="left" valign="top"></td>
    <td align="right" valign="top">
	 <%= link_to "Cancel", edit_user_path(current_user),:class =>"deal",:style=>"float:right; margin-left:10px" %>
      <%= f.submit 'Change E-Mail Address',:class=>"deal",:style=>"float:right" %> 
	    </td>
  </tr>
</table>
<% end %>
</div>

   </div>
    </div>

app/views/users/help.html.erb
<div class="tutorial_container" style="padding:20px 10px">
  <div class="righttd" style="margin-bottom:20px"><strong><div class="title">Contact</div></strong>
  </div>

  
  <div>

<table width="520" border="0" cellspacing="10" cellpadding="0" style="font-size:18px">
<strong><div class="txt" style="color:#000000">  Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam arcu magna, luctus in feugiat nec, ullamcorper eu metus. </div></strong>
</p><strong><div class="txt"> Cras vitae diam eros. Mauris tempus auctor commodo. Aliquam facilisis tristique augue sed cursus. Morbi faucibus volutpat augue eget tempor. Vestibulum risus orci, rutrum ac auctor ac, convallis vel orci. Donec dignissim libero orci, ut porta eros. Cras vitae diam eros. Mauris tempus auctor commodo. Aliquam facilisis tristique augue sed cursus. Morbi faucibus volutpat augue eget tempor. Vestibulum risus orci, rutrum ac auctor ac, convallis vel orci. Donec dignissim libero orci, ut porta eros.  
</div></p></strong>

	
	
	


      
    
</table>

</div>
</div>

    </div>

app/views/users/how_it_works.html.erb
<div class="tutorial_container" style="padding:20px 10px">
  <div class="righttd" style="margin-bottom:20px"><strong><div class="title">How it works</div></strong>
  </div>

  
  <div>

<table width="520" border="0" cellspacing="10" cellpadding="0" style="font-size:18px">
<strong><div class="txt">  Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam arcu magna, luctus in feugiat nec, ullamcorper eu metus. Cras vitae diam eros. Mauris tempus auctor commodo. </div></p></strong>
<strong><div class="txt">Aliquam facilisis tristique augue sed cursus. Morbi faucibus volutpat augue eget tempor. Vestibulum risus orci, rutrum ac auctor ac, convallis vel orci. Donec dignissim libero orci, ut porta eros. Quisque fermentum, nisi vel molestie ultrices, sapien mi semper felis, id porta lorem lacus non risus. Donec tellus diam, aliquet in mollis quis, dapibus in arcu. Nullam placerat aliquam dui. Vivamus nibh lectus, iaculis a rhoncus ut, pharetra in metus. Lorem ipsum dolor sit amet, consectetur adipiscing elit Nullam arcu magna, luctus in feugiat nec, illamcorper Cras vitae diameros. Mauris tempus auctor commodo</div></p></strong>
	
	<div class="txt1">
	<ul style="color:#000000">
	<strong><li>Aliquam condimentum augue in neque dictum id adipiscing tellus tempus.</li></strong>
	<strong><li>Praesent vestibulum facilisis eros, et tempus leo imperdiet sit amet.</li></strong>
	<strong><li>Sed iaculis magna sed lectus pulvinar sodales.</li></strong>
	<strong><li>Suspendisse ultrices posuere tortor, ac pretium ante pretium nec.</li></strong>
	<strong><li>Etiam vel urna ligula, at porta velit.</li></strong>
	<strong><li>Praesent a turpis ac metus consectetur porta ullamcorper ut magna.</li></strong>
	</ul></div>


      <strong><div class="txt">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam arcu magna, luctus in feugiat nec, ullamcorper eu metus. Cras vitae diam eros. Mauris tempus auctor commodo. Aliquam facilisis tristique augue sed cursus. Morbi faucibus volutpat augue eget tempor. </div></strong>
  
    
</table>

</div>

     </div>
    </div>

app/views/users/my_profile.html.erb
<div class="tutorial_container2">
   	 <div class="leftmenu_div">
			<div style="text-align:center; margin:20px 0 "><h1>My Account</h1></div>
			<ul id="blueblock">
				<li><a href="#">Account Setting</a></li>
			</ul>
	</div>
		
	<div class="rightside_div">
		
	<div class="profile_wrap">
	
	<table width="100%" border="0" cellspacing="5" cellpadding="5">
 	 <tr>
   
 	 </tr>
	  <tr>
   
 	 </tr>
 	
 	 <tr>
  	  <td><%= link_to "Change my password",  change_password_path,:class =>"cp" %><br />
   	  <%= link_to "Change my email address", edit_user_path(current_user),:class =>"cp" %></td>
 	 </tr>

</table>

	</div>
	</div>
	
	</div>
    </div>

app/views/users/new.html.erb
<h1>Sign up</h1>
<%= form_for(@user, :html => {:id => "signup"}) do |f| %>
<%= render 'shared/error_messages', :object => f.object %>

<div class="field">
<%= f.label :name %><br />
<%= f.text_field :name %>
</div>
<div class="field">
<%= f.label :email %><br />
<%= f.text_field :email %>
</div>
<div class="field">
<%= f.label :password %><br />
<%= f.password_field :password %>
</div>
<div class="field">
<%= f.label :password_confirmation, "Confirmation" %><br />
<%= f.password_field :password_confirmation %>
</div>
<div class="actions">
<%= f.submit "Sign up" %>
</div>
<% end %>

app/views/users/show.html.erb
<table class="profile" summary="Profile Information"> 
	<tr>
		<td class ="main">
			

			</td>
			<td class="sidebar round">
				<strong>User Name </strong>    <%= current_user.name %><br/>
				<strong> Email  </strong>  <%= current_user.email %><br/><br/>
				
				<a href="/users/<%= current_user.id%>/edit" >Edit</a><br>
				<%= link_to 'change password', change_password_path%>
			</td>
	</tr>

</table>