config/routes.rb
DemoCloud::Application.routes.draw do 
 
  mount Ckeditor::Engine => '/ckeditor'

  resources :comments
  
  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

 resources :authentications
 
 resources :courses do
   post "rate", :on=> :member
 end
 
 match "pages/:id" ,:to => "pages#show"
 
 match '/auth/:provider/callback' => 'authentications#create' 
 match '/users/validations/check_email', :to=>"users#check_email"
 
 get "password_resets/new"

 match '/change_password', :controller => 'users', :action => 'change_password'
 
  match 'users/my_profile' ,:to =>'users#my_profile'
  match 'users/about_us' ,:to =>'users#about_us'
  match 'users/help' ,:to =>'users#help'
  match 'users/how_it_works' ,:to =>'users#how_it_works'
  match 'users/account_setting' ,:to =>'users#account_setting'
 resources :users do
    get "is_authenticated", :on=> :member
 end
  
  resources :sessions, :only => [:new,:create,:destroy,:edit]
  
  root :to => 'homes#index'
  
  match 'dashboard' => 'users#dashboard', :as => 'user_root'
  match '/user_signup', :to =>'users#new'
  match '/user_signin', :to =>'sessions#new'
  match  '/users/:id/edit',  :to => "users#edit" 
  match '/user_signout', :to =>'sessions#destroy'
  
  resources :password_resets

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
<title>CoderSave - cheap programming tutorials</title>
<%= javascript_include_tag 'application', 'jquery-1','jquery.validate.min' %>
<%= stylesheet_link_tag  "signup-login.css", "style.css", "bootstrap.css"  %>
<%= csrf_meta_tag %>

<!-- Sign Up window flip script Start here -->
<script type="text/javascript">
    function replaceEmailField(address) {
      $('#emailinput').val(address);
      $('#emailinput').focus();
      $('#capture').submit();
    }

    function displayLogin() {
      $('#register').hide();
      $('#login').show();
      $('.logindiv h3.hook').html("<a class='btn' href='javascript:void(0);' onclick='displayRegister();'>Sign Up</a>");
    }
    
    function displayRegister() {
      $('#login').hide();
      $('#register').show();
      $('.logindiv h3.hook').html("Already a member? <a href='javascript:void(0);' onclick='displayLogin();'>Log in</a>");
    }
    
    $(document).ready(function() { 
      $('input[name=email]').attr('placeholder', 'Enter your email');
      $('input[name=password]').attr('placeholder', 'Enter your password');
      

      $('.facebook_connect').click(function(e) {      
        var fb_permissions = {scope: 'email,user_birthday,user_location,publish_stream,publish_actions,user_interests,user_likes'};                
        FB.login(function(response) {
          if (response.authResponse) {
            document.location = document.location.protocol+'//'+document.location.host+'/account/login/?fblogin=1&next=/account/';
          }
          return true;
        }, fb_permissions);        
        e.preventDefault();
      });
  
      $("#emailinput").focus();

      function IsValidEmail(email) {
        var filter = /^([\w-\.\+]+)@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.)|(([\w-]+\.)+))([a-zA-Z]{2,4}|[0-9]{1,3})(\]?)$/;
        return filter.test(email);
      }

      $("#emailinput").focusout(function() {
        $(this).mailcheck({
          suggested: function(element, suggestion) {
            $('.email_suggestion').html("Did you mean <a href='javascript:void(0);' onclick='replaceEmailField(\"" + suggestion.full + "\")'>" + suggestion.address + "@<b>" + suggestion.domain + "</b>?</a>").show();
          },
          empty: function(element) {
            $('.email_suggestion').hide();
          }
        });
      });

      $('form#capture').submit(function() {
        var sug = false;
        var email = $.trim($(this).find('input[type="text"]').val());
        $(this).find('input[type="text"]').val(email)
        if(email == '') {
          $('#capture h3.error').html('<span style="color: red;">We\'re gonna need an email address, buddy.</span>');
          return false;
        } else {
          $('#emailinput').mailcheck({
            suggested: function(element, suggestion) {
              if ($('.email_suggestion').is(':visible')) {
                sug = false;
              }
              else {
                sug = true;
                $('.email_suggestion').html("<br /><a href='javascript:void(0);' onclick='replaceEmailField(\"" + suggestion.full + "\")'>" + suggestion.address + "@<b>" + suggestion.domain + "</b>?</a>").show();
              }
            },
            empty: function(element) {
              $('.email_suggestion').hide();
            }
          });

          if (sug) {
            return false;
          }
          else {
            if(IsValidEmail(email)) {
              $('#capture h3.error').html('<span style="color: green;">Hooray!</span>');
              return true;
            } else {
              $('#capture h3.error').html('<span style="color: red;">We\'re gonna need a legit email address, buddy.</span>');
              return false;
            }
          }
        }
      });
    });
  </script>
<!-- Sign Up window flip script Ends here -->
</head>
<body>

<div align="center" id="maindiv">
	 <div class="top_right_menu" style="margin:20px 20px 0 0">
  				<a href="/pages/about-us">About us</a>&nbsp;&nbsp;
       <a href="/pages/how-it-works">How it works</a> &nbsp;&nbsp;
       <a href="/pages/contact">Contact</a> 
     </div>
  <div align="center" id="wrapper">
  	
     <div id="frontlogo"><%= link_to image_tag('/assets/front_logo.png'), root_path %>
	
	<div class="discount_line">Discounts on the best programming courses. <br />
	<span class="discount_red">Up to 70% OFF!</span></div>
	
	</div>
	 	<div id="loginbox">
     	 <div style="display: block;" id="login" class="logindiv">
	 		 <h1>Member Login</h1>
	  			<div class="fb"><a class="bt-fb-login facebook_connect" href="/auth/facebook" style="border:0;margin-left:auto;margin-right:auto;"></a></div>
	  			
	  				<div>Or sign in with your coder save account</div>
	  					<!---Sign In form Starts here-->
	  						<%= form_for(:session, :url => sessions_path, :html => {:id => "signin"}) do |f| %>
	 							 <div class="labeldiv"> Email 
									<%= f.text_field :email, :class => "logintf", :placeholder => "Enter Your Email" %>
	 							  </div>
	  
	  							  <div class="labeldiv"> Password
	 								<%= f.password_field :password, :class => "logintf", :placeholder => "Enter Your Password"  %>
	  							  </div>
	  							<div>
	  								<%= f.submit "Log in", :class=> "btn" %>
	  
	  						<% end %>
						  <!---Sign In form Ends here-->  
	  							 </div>
	  		</div>
	  	<div id="register" style="display: none; text-align:left">
          	<h1 class="headline">Join Today!</h1>
		  
          	<div id="emcollect">
            
              <div style="display:none"><input name="csrfmiddlewaretoken" value="e4780374297942de7c7d610d281d1620" type="hidden"></div>
              <a class="bt-fb-join facebook_connect" href="/auth/facebook" style="border:0;margin-left:auto;margin-right:auto;"></a>
              <div>Or </div>
            <%= form_for(:user, :url => {:controller=>"users", :action=>"create"}, :html => {:id => "signup"}) do |f| %>
              <div class="labeldiv"> Email 
              	<%= f.text_field :email, :class => "logintf", :placeholder => "Enter Your Email."  %>
			  </div>
			  <div class="labeldiv"> Password 
			    <%= f.password_field :password,  :class => "logintf", :placeholder => "Enter Your Password." %>
			  </div>
			  <div class="labeldiv"> Password Confirmation
			    <%= f.password_field :password_confirmation,  :class => "logintf", :placeholder => "Confirm Your Password." %>
			  </div>
			  <%= f.submit "Sign up", :class => "btn" %>
            <% end %>
            
          </div>
        </div>
        
        <div style = "text-align :left; color :red" >
        
          <% flash.each do |key, msg| %>
            <div id="<%= key %>">   
              <p><%= msg %></p>
              <div class="clear"></div>
            </div>
          <% end %>
         </div>
	  
	   
	  <div class="divider"></div>
	  
	  <div class="logindiv" style="display: block;" id="login">
	  
	  <h1>Become a Member</h1>
	   <div class="membership">Get up to 70% OFF on best programming courses on the web! <span class="white_txt">Memberships is FREE</span></div>
	   
	   <div>
	    <h3 class="hook"><a class="btn" href="javascript:void(0);" onClick="displayRegister();">Sign Up</a></h3>
	  </div>
	  
	  </div>
  </div>
	<div class="b_shadow"></div>
  </div>
  
  <div class="course_preview_bg">
  <div class="course_preview_heading">Courses Preview</div>
  	<% @courses = Course.all %>
   
    <div class="course_preview_wrap">
    	
	<ul class="discover-courses-list">
	   <% @courses.each do |course|  %>
	<li>
       <a class="mask" href="/courses/<%= course.id %>">
         <span style="background-image: url( <%=course.image_url(:thumb)%>)" class="course-thumb">
               <span>
                 <span>View This Course</span>
               </span>
           </span>
                <span class="main-info">
                    <h3><%= truncate(course.course_title, :length => 28) %> </h3>
                    <h4>
                        
                        <span class="title ellipsis"><%= course.headline %>  </span>
                        <span class="job-title ellipsis"><%= truncate(course.goals_objectives, :length => 50).html_safe %></span> 
                    </h4>
                </span>
                <span class="course-info">
                 <%= truncate(course.course_summary, :length => 120) %></span> 
                </a>
     </li>
			<%end%>							
				
	</ul>

	
	</div>
  
  </div>
  <div class="footer_wrap">
 <div class="footer">
  <div style="width:40%; float:left; text-align:left">
  	Codersave.com <img src ="/assets/copyright.png" >&nbsp;2012 &nbsp;&nbsp; <a href="/pages/terms">Terms </a> &nbsp;|&nbsp; <a href="/pages/privacy">Privacy </a>
  	
   	
  </div>
  <div style="width:40%; float:right">
  	 
  	
  </div>
  
  </div>
  
  </div>
</div>
</div>
</body>
</html>

app/views/layouts/courses.html.erb
<!DOCTYPE html>
<html>
<head>
<title>CoderSave - cheap programming tutorials</title>
<%= stylesheet_link_tag  "ajaxful_rating.css","style2.css"%>
   
<%= javascript_include_tag 'application' %>
<%= ajaxful_rating_style %>
<%= yield :styles %>

<%= yield :scripts %>


<%= csrf_meta_tag %>

</head>
<body>
<div align="center" id="maindiv">
		<div align="center" id="wrapper">

  			<div id="header">
			
	<div id="logo2">
		<% if signed_in? %>
			<%= link_to image_tag('/assets/logo2.png'), user_root_path %>
		<% else %>
			<%= link_to image_tag('/assets/logo2.png'), root_path %>
		<% end %>
	</div>
	
	<div class="top_right_menu">
		<%= current_user.email rescue "" %>
		<% if signed_in? %> 
			<%= link_to "Home", user_root_path %>
		<% end %>	   
		<a href="/pages/about-us">About us</a>
 		<a href="/pages/how-it-works">How it works</a> 
 		
 		<% if signed_in? %>
			<%= link_to "My Account", users_my_profile_path %>
		<% end %>
		        
		    
        <a href="/pages/contact">Contact</a>    
		<% if signed_in? %>     
			<%= link_to "Logout", user_signout_path %>
		<% end %>
	</div>

<%= yield %>
 <div class="footer_wrap">
 <div class="footer">
  <div style="width:40%; float:left; text-align:left">
  	Codersave.com <img src ="/assets/copyright.png" >&nbsp;2012 &nbsp;&nbsp; <a href="/pages/terms">Terms </a> &nbsp;|&nbsp; <a href="/pages/privacy">Privacy </a>
  	
   	
  </div>
  <div style="width:40%; float:right">
  	
  	
  </div>
  
  </div>
  
  </div>
</div>
</div></div>


</body>
</html>

app/views/layouts/dashboard.html.erb
<!DOCTYPE html>
<html>
<head>
<title>CoderSave - cheap programming tutorials</title>
<%= stylesheet_link_tag  "ajaxful_rating.css","style2.css"%>
   
<%= javascript_include_tag 'application' %>
<%= ajaxful_rating_style %>
<%= csrf_meta_tag %>

</head>
<body>
<div align="center" id="maindiv">
		<div align="center" id="wrapper">

  			<div id="header">
			
	<div id="logo2">
		<% if signed_in? %>
			<%= link_to image_tag('/assets/logo2.png'), user_root_path %>
		<% else %>
			<%= link_to image_tag('/assets/logo2.png'), root_path %>
		<% end %>
		
	</div>

<div class="top_right_menu">
	<%= current_user.email rescue "" %>
	<% if signed_in? %>  
		<%= link_to "Home", user_root_path %>
	<% end %>	 
			<a href="/pages/about-us">About us</a>
 	        <a href="/pages/how-it-works">How it works</a>
 	<% if signed_in? %> 
		<%= link_to "My Account", users_my_profile_path %>
	<% end %>        
	<a href="/pages/contact">Contact</a>

	<% if signed_in? %>     
		<%= link_to "Logout", user_signout_path %>
	<% end %>
	</div>
</div>

<%= yield %>
 <%- flash.each do |key, msg| -%>
  <div id="<%= key %>">
   
    <p><%= msg %></p>
    <div class="clear"></div>
  </div>
<%- end -%>
<div class="footer_wrap">
 <div class="footer">
  <div style="width:40%; float:left; text-align:left">
  	Codersave.com <img src ="/assets/copyright.png" >&nbsp;2012 &nbsp;&nbsp; <a href="/pages/terms">Terms </a> &nbsp;|&nbsp; <a href="/pages/privacy">Privacy </a>
  	
   	
  </div>
  <div style="width:40%; float:right">
  	
  	
  </div>
  
  </div>
  
  </div>
  </div>
</div>
</body>
</html>